### ISSUE TITLE
获取不到Read_Master_log_Pos值

### ISSUE THREAD

**Issue by 1029649360** [n9e/mymon#2]
2020/04/01 11:13:03.866 [I] [main.go:152] Send response 192.168.99.100:3306 - {"err":"metric:\u003cMetaData Endpoint:192.168.99.100, Metric:mysql.Read_Master_log_Pos, CounterType:GAUGE Timestamp:1585710781, Step:60, **Value:\u003cnil\u003e**, Tags:isSlave=1,port=3306,readOnly=0,type=mysql(map[isSlave:1 port:3306 readOnly:0 type:mysql])\u003e err:value is not illegal:\u003cMetaData Endpoint:192.168.99.100, Metric:mysql.Read_Master_log_Pos, CounterType:GAUGE Timestamp:1585710781, Step:60, Value:\u003cnil\u003e, Tags:isSlave=1,port=3306,readOnly=0,type=mysql(map[isSlave:1 port:3306 readOnly:0 type:mysql])\u003e"}

**Comment by UlricQin** [comment]
这个插件上报的部分数据有问题，应该只影响部分指标

**Comment by 1029649360** [comment]
现在发现这个endpoint的值应该都没有推送成功
![image](https://user-images.githubusercontent.com/45092668/78097059-d975e300-740d-11ea-908f-19c1e45acafa.png)

**Comment by 1029649360** [comment]
应该是show slave status\G的值没有推送成功

**Comment by UlricQin** [comment]
打开DEBUG级别的日志，看看推送的内容都是啥

**Comment by 1029649360** [comment]
看DEBUG信息，是投推送了，但是监控看图里面没有slave的数据。看了几个slave的信息，是没有

**Comment by UlricQin** [comment]
需要看推送的内容是什么，看起来是不符合夜莺的监控数据格式要求。而根因，应该是mymon获取的mysql的数据有问题

**Comment by 1029649360** [comment]
好的，我再找找原因。

**Comment by xuclachina** [comment]
metric.go中
var SlaveStatus = []string{
	"Exec_Master_Log_Pos",
	"Read_Master_log_Pos",
	"Relay_Log_Pos",
	"Seconds_Behind_Master",
	"Slave_IO_Running",
	"Slave_SQL_Running",
}
Read_Master_log_Pos改成Read_Master_Log_Pos然后重新编译即可

**Comment by xuclachina** [comment]
> 好的，我再找找原因。

metric.go中
var SlaveStatus = []string{
"Exec_Master_Log_Pos",
"Read_Master_log_Pos",
"Relay_Log_Pos",
"Seconds_Behind_Master",
"Slave_IO_Running",
"Slave_SQL_Running",
}
Read_Master_log_Pos改成Read_Master_Log_Pos然后重新编译即可

**Comment by UlricQin** [comment]
@xuclachina  来个PR可好？：）

**Comment by UlricQin** [comment]
多谢 @xuclachina 共建社区之举 ：）
